apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: coole-webapp
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`cw-test.internal`)
      priority: 10
      services:
        - name: coole-webapp
          port: 80
