---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password-secret
  namespace: coole-webapp
spec:
  encryptedData:
    .db_password: AgCeyK3ZpM2Xzzdyc0EQBTSZjnyGI5u3RxfpQgtfpSGSvaWc4mMBlxlY4FQMaShgjXR/AL7gf2UhaT3PNvtjBwwLPyAy/6vrpX3LsLfPs87CaToI1hQgiibDSnUZAkPVkeezMTbCZZFtwhH+7oc6RZ7orwZXjTKU87dY+Nwa/00S3nqbbgHLM2b/CHyF6fehBTeW8/Vv2KdBaWs2OVjmJj7EK/B4DZocO+MyVjNAyEq4DJiHGpy3mBkY0dl5K+lTz9PqZCKxAkEw6OJyAokyEcHoelRPdxzbzPBIX7Bd07PV7jYlwLi6unnY/jPdZCzcOeIpQYeHI0iNJuI0UuHz5RbvGP5DNpSZAGBnypA7jeIlb9IyR8kGwsJFTHa4ObyreGHf7a445Xa0XXEbbRb5J6ITPS1NYYZbT/nGhK6Z/hre/GnPNDhcCVb3ByIE2J2KMqCDb1AGnzod4vXZWShjGm8dxiD+ybri0Nyn59lvO3bcRSgXuioxkz19PjbvERrdnmU0T5eecnSAiRsZaMxEnjt+o0wkDIi2UikjQdc30jls5mZJquOnuZU5ZEYbizr7IBpLvICSLeBjomth2D4gHInhMYMACGUwfnMhV5dp5LLNjt3GY0ldU7KjV0woPWjqqv8sbarGJmDo2r/VEEPpxZIT8/XadM6oPwRuNGpxMAgidhQE7CqnVn5U+ExZNYzuN/CZPdAc7ORqDfOscB3rTPwbZUc=
    .db_root_password: AgAGn1rfekGwYn96R1DoU2F8l1dMbNzq3iZx5Cvja58vUTh1Lj/qwnnoLsAZaCByVoStDXNnuZfxWQACHmvuK6R7DTfMX3MJbcLMBGBpSrMGwNWEHfRpy1Q8el50lKSasVceiYCYaT4PqlLrdvN84J4GcOrxT2yT67gxsEgwhspDg8Yl403b1msglBpsvTnz8fKK0CNmuzNoiNMSWBxHtGx1Qu+Fgvzp0YDPsE+uCx/hBu/ErJ9sqL2rW+10L8wOTC/u0Td4eID0lz5bWH7jxxl3iQO4HSMyblSsL/+T7LYjy5pw2mMHbedZju1IU4cDRFQzhmtvKQZyyjNqoixD2WqJasNxGf73BIZ1M8l74//nWiiksE1xpa3TSk18I4up/CYj4x0v1ELazutS7OAzyK4XIX2zi8DaOXmKRXLL6ZtSgInsDUm0lD+FtuTX/3T0pQh2pl2gjjmPHwLLTxwAtRfLGF3BqSIRUCMn3Maf1z1kbX8H16cNK3zmid9BQY3H1FQYXXfO1AdCFA1KpPB6s2D1JePb1KP+tX7+/OIKkbFwFBEoe7LcV6S1ncb2yC++hMOLG+3yUy0mPtqTgRTQqjDrTGaajhQjY413qXZGGJpm0IKxSsT2GSxBXRQrfMybQBGjEXe9QXLvOjbPu7DQEON04qjh7Rt2L4+YmclBe50mu7pwvWHiKMmtTPPZYhh5+hFQzI70qOSc03W93RR5VVchhrQ=
  template:
    metadata:
      creationTimestamp: null
      name: db-password-secret
      namespace: coole-webapp
    type: Opaque
