apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /etc/secrets/.db_root_password
            - name: DB_PASSWORD_FILE
              value: /etc/secrets/.db_password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
            - mountPath: /etc/secrets
              name: postgres-secret-volume
              readOnly: true
            - mountPath: /docker-entrypoint-initdb.d/init-user-db.sh
              subPath: init-user-db.sh
              name: postgres-init-config
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
        - name: postgres-secret-volume
          secret:
            secretName: db-password-secret
        - name: postgres-init-config
          configMap:
            name: postgres-init-config
